#version: '3.8'
#
#services:
#  invoice-management-app:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    image: openjdk:17-jdk
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/my_pgdb
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password
#    depends_on:
#      - postgres
#
#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: my_pgdb
#    ports:
#      - "5432:5432"
#

# version: '3.8'

# services:
#   app:
#     build: .
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/my_pgdb
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: password
#       SPRING_JPA_HIBERNATE_DDL_AUTO: update
#       SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
#     ports:
#       - "8081:8081"
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: my_pgdb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5433:5432"

